version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=192.168.1.210
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=client_management
    restart: always
    volumes:
      - "D:/Docker/Client_management_0.5:/app/data"

# No named volumes needed unless you're storing persistent DB data
